### ISSUE TITLE
你好，请问怎么确定每次提交后运行成功呢?

### ISSUE THREAD

**Issue by PengRui1995** [zhule0601/glados_checkin#1]
你好，我在fork之后将 yml 中的时间设置为 每隔10 min 执行一次，但我发现每次工作流执行成功后，build 中“check in”中的内容没有变化，因此我不确定是否签到成功了。我不太清check in 日志修改机制是啥，请问你可以解释一下么，谢谢你！

**Comment by zhule0601** [comment]
每天只能签到一次, 前30天, 100%成功率,. 30天后, 每天签到 30% 成功概率.
签到成功日志中会显示: Get 1 Day.
