### ISSUE TITLE
近日签到接连失败（不是概率原因，似乎是被cloudflare挡住了？）

### ISSUE THREAD

**Issue by jerrywcy** [zhule0601/glados_checkin#3]
您好！
非常感谢您开发了这个自动签到脚本，然而近日似乎签到接连失败，而且不是概率原因，而是result返回了一串HTML文档。报错如图：
<img width="656" alt="image" src="https://user-images.githubusercontent.com/34678939/176385944-3d71e5e5-3723-4d5c-820f-57c7b045792f.png">
我把HTML复制出来发现似乎是Cloudflare的跳转页面，如图：
![image](https://user-images.githubusercontent.com/34678939/176386483-089df542-06fc-4187-a00a-4bdcd3b2cf66.png)

**Comment by zhule0601** [comment]
已经更新了代码,  拉取最新代码后可以解决

**Comment by jerrywcy** [comment]
可以了！万分感谢！
